version: "3"

services:
  # creates OpenVPN Docker container to first provider that randomly picks .conf file
  ovpn_01:
    image: ghcr.io/wfg/openvpn-client:2.1.0
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z
      - ./openvpn/:/data/vpn:z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      KILL_SWITCH: "on"
      HTTP_PROXY: "off"
      VPN_AUTH_SECRET: provider01_secret
      VPN_CONFIG_PATTERN: provider01*.conf # this will match provider01_country01.conf, provider01_country02.conf etc
    secrets:
      - provider01_secret

  # creates OpenVPN Docker container to first provider with specific .conf file
  ovpn_02:
    image: ghcr.io/wfg/openvpn-client:2.1.0
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z
      - ./openvpn/:/data/vpn:z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      KILL_SWITCH: "on"
      HTTP_PROXY: "off"
      VPN_AUTH_SECRET: provider01_secret
      VPN_CONFIG_FILE: provider01.endpoint02.conf # will use only this .conf file
    secrets:
      - provider01_secret

  # creates OpenVPN Docker container to second provider with specific .conf file
  ovpn_03:
    image: ghcr.io/wfg/openvpn-client:2.1.0
    cap_add:
      - NET_ADMIN
    security_opt:
      - label:disable
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z
      - ./openvpn/:/data/vpn:z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      KILL_SWITCH: "on"
      HTTP_PROXY: "off"
      VPN_AUTH_SECRET: provider02_secret
      VPN_CONFIG_FILE: provider02.endpoint01.conf # will use only this .conf file
    secrets:
      - provider02_secret

  # this Docker container will use VPN 01
  db1000n_01:
    image: ghcr.io/arriven/db1000n-advanced
    restart: unless-stopped
    depends_on:
      - ovpn_01
    network_mode: "service:ovpn_01"

  # this Docker container will use VPN 02
  db1000n_02:
    image: ghcr.io/arriven/db1000n-advanced
    restart: unless-stopped
    depends_on:
      - ovpn_02
    network_mode: "service:ovpn_02"

  # this Docker container will use VPN 03
  db1000n_03:
    image: ghcr.io/arriven/db1000n-advanced
    restart: unless-stopped
    depends_on:
      - ovpn_03
    network_mode: "service:ovpn_03"

secrets:
  provider01_secret:
    file: ./openvpn/provider01.txt
  provider02_secret:
    file: ./openvpn/provider02.txt
