---
apiVersion: v1
kind: Namespace
metadata:
  name: db1000n

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db1000n
  namespace: db1000n
  labels:
    app: db1000n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db1000n
  template:
    metadata:
      labels:
        app: db1000n
    spec:
      containers:
        - name: db1000n
          image: ghcr.io/arriven/db1000n-advanced:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "2"
